[package]
name = "skyzen-hyper"
version = "0.1.1"
edition = "2021"
description = "Hyper server backend for the Skyzen framework"
license = "MIT OR Apache-2.0"
repository = "https://github.com/zen-rs/skyzen"
readme = "README.md"
keywords = ["http", "web", "framework"]
categories = ["web-programming::http-server"]

[dependencies]
skyzen-core.workspace = true
http-kit.workspace = true
futures-util = "0.3.32"
http-body = "1.0"
http-body-util = "0.1.3"
executor-core.workspace = true
tracing.workspace = true
async-io.workspace = true

[dependencies.hyper]
features = ["server", "http1", "http2"]
version = "1.8"
default-features = false

[dev-dependencies]
tokio = { version = "1.49", features = ["macros", "rt-multi-thread", "signal", "io-util"] }
smol.workspace = true
executor-core = { workspace = true, features = ["smol"] }

[lints]
workspace = true
